version: "3.9"
services:
  db:
    image: postgres
    container_name: candidates-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake db:exists && rake db:migrate || rake db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/candidates
    ports:
      - "3000:3000"
    depends_on:
      - db